### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by kosowski** [meta-meta/p5-Rift#1]
Gradle build script is not working for me. For some reason it tries compiling the dependencies before cloning them. Tried cloning them manually, but still fails as it is unable to find any folder outside the p5-Rift folder:

Im running "Gradlew setup" from inside the "p5-Rift" folder, and getting this error on line 28.

"Project with path ':../p5-VR' could not be found in root project 'p5-Rift'." But the p5-VR folder is where it should be.

Thanks!

**Comment by meta-meta** [comment]
Thanks @kosowski I had one of the cloned directories named wrong. Try now. And get in touch if you have further issues or questions. The script will appear to hang on Building 0%... the repo for Processing is over a gig.

Examples of how I use this are here: https://github.com/meta-meta/OculusRiftSandbox/tree/master/src/main/java/com/generalprocessingunit/processing/demos/vr

Example.java is the simplest and doesn't use any additional hardware.

**Comment by meta-meta** [comment]
I just tested. Ran into an error "Bad <init> method call from inside of a branch."  I believe this is due to a Java update. I'm running Java 8 now. If you run into this, just 

``` bash
cd ../processing
git checkout riftIntegration
cd ../p5-Rift
gradlew setup
```

**Comment by kosowski** [comment]
Thanks @meta-meta. I moved to the OculusRiftSandbox repo and was able to run the gradle script and import the project into IntelliJ. I'm having some troubles to configure Intellij, some of the demos can be run as applications, but others only as applets, even though they have a main().

When trying to run any of the demos as an application I get the following output

`Uncaught error fetching image:
java.lang.NullPointerException
    at sun.awt.image.URLImageSource.getConnection(URLImageSource.java:115)
    at sun.awt.image.URLImageSource.getDecoder(URLImageSource.java:125)
    at sun.awt.image.InputStreamImageSource.doFetch(InputStreamImageSource.java:263)
    at sun.awt.image.ImageFetcher.fetchloop(ImageFetcher.java:205)
    at sun.awt.image.ImageFetcher.run(ImageFetcher.java:169)`

It would be a lot simpler if you could compile the library. Will keep trying to get it running and report back.

**Comment by meta-meta** [comment]
You might need to install scala and the scala plugin. Sorry that's kinda my
playground so there's a lot of stuff you probably don't care about.
Alternately you could remove the MusicalLibrary and p5-Musical modules and
delete MusicStaffTest.java (I think that's all that I'm using those modules
for)

Otherwise, if you'd like I could push up a barebones example project
without any of the extra stuff.

**Comment by kosowski** [comment]
Thanks Paul, maybe a barebones examples I can set up in Eclipse could be a better starting point.

About Scala, although it is included as a module dependency, I had to install the SDK, remove the dependency and set up a new one pointing to the installed SDK.

**Comment by meta-meta** [comment]
"About Scala, although it is included as a module dependency, I had to
install the SDK, remove the dependency and set up a new one pointing to the
installed SDK."

Does that mean you got it to build? I wouldn't mind walking you through the
code on Skype since you've been so persistent. Not sure I'll have time to
make a barebones example for a little while.

**Comment by kosowski** [comment]
Yes, I build it, it was just installing the Scala SDK. I mentioned the error I was having when running any of the demos after succesfully building the project.

When I can put some time on this I'll try to set an Eclipse project with the barebones of your projects. If you manage to find the time for making a basic example, I would like to hear from you. Thanks Paul!
